# netlify.toml

[build]
  command   = "npm run build"    # hoặc "pnpm run build"
  publish   = ".next"            # thư mục build mặc định của Next.js

# Đăng ký plugin Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"            # đảm bảo Node.js 18.x
