# netlify.toml

[build]
  # Dùng script CI (alias chạy build + export)
  command   = "pnpm run build:ci"
  # Netlify sẽ publish từ thư mục 'out'
  publish   = "out"

[build.environment]
  # Ép Netlify dùng Node.js 18.x
  NODE_VERSION = "18"
