# netlify.toml

[build]
  # Lệnh build tạo ra folder .next
  command   = "pnpm run build:ci"       # hoặc "pnpm run build"
  # Netlify sẽ publish từ đây
  publish   = "out"

# Ép Netlify dùng Node 18 để phù hợp engines.node
[build.environment]
  NODE_VERSION = "18"
